# Generated by Django 2.0.3 on 2019-03-19 09:06

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_messages', '0007_channel_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='channel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 19, 9, 6, 3, 369611)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
