# Generated by Django 2.1.7 on 2019-03-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_messages', '0008_auto_20190319_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
