# Generated by Django 2.1.7 on 2019-03-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_messages', '0009_auto_20190320_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
