# Generated by Django 2.1.7 on 2019-03-20 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_messages', '0013_auto_20190320_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['channel_date']},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='date',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
